namespace Optimus.Core.Corel
{
    /// <summary>
    /// VGCore enum values, every one of them READ FROM THE TYPELIB, never guessed.
    ///
    /// <para>
    /// Source of truth: <c>docs/vgcore-tlb-dump.txt</c> (VGCore 25.2). Before adding or changing a
    /// value here, grep that file. The dump is regenerated by <c>docs/dumptlb.ps1</c>.
    /// </para>
    /// <para>
    /// WHY THIS FILE EXISTS: guessing <c>cdrMillimeter</c> as 4 (it is 3 — 4 is
    /// <c>cdrCentimeter</c>) puts the document in centimetres, so every coordinate and every
    /// tolerance is off by 10x. It broke SisCut once (nesting came out horizontal) and shipped
    /// again in Optimus v1.0, where it silently made the "0.03 mm" tolerance 0.3 mm.
    /// </para>
    /// <para>
    /// These live in Core (not Interop) on purpose: they are plain data, so they stay testable
    /// from the net8.0 test project, which cannot reference a net48 assembly.
    /// </para>
    /// </summary>
    public static class CorelConstants
    {
        // ── cdrUnit ─────────────────────────────────────────────────────────────────────
        /// <summary><c>cdrUnit.cdrMillimeter</c> = 3. NOT 4 — see the class remarks.</summary>
        public const int CdrMillimeter = 3;

        /// <summary><c>cdrUnit.cdrCentimeter</c> = 4. Kept explicit so the difference is visible.</summary>
        public const int CdrCentimeter = 4;

        // ── cdrShapeType ────────────────────────────────────────────────────────────────
        public const int CdrRectangleShape = 1;
        public const int CdrEllipseShape = 2;

        /// <summary><c>cdrCurveShape</c> = 3. A v1.0 comment claimed 5, which is a bitmap.</summary>
        public const int CdrCurveShape = 3;

        public const int CdrPolygonShape = 4;
        public const int CdrBitmapShape = 5;
        public const int CdrTextShape = 6;
        public const int CdrGroupShape = 7;
        public const int CdrBlendGroupShape = 10;
        public const int CdrExtrudeGroupShape = 11;
        public const int CdrOleObjectShape = 12;
        public const int CdrContourGroupShape = 13;
        public const int CdrBevelGroupShape = 15;
        public const int CdrDropShadowGroupShape = 16;
        public const int CdrArtisticMediaGroupShape = 18;
        public const int CdrMeshFillShape = 20;

        /// <summary><c>cdrCustomShape</c> = 21. Was missing entirely until a real document hit it.</summary>
        public const int CdrCustomShape = 21;
        public const int CdrCustomEffectGroupShape = 22;
        public const int CdrSymbolShape = 23;
        public const int CdrPerfectShape = 26;
        public const int CdrEpsShape = 27;

        // ── cdrThumbnailSize (save-time size lever, Phase 3) ────────────────────────────
        public const int CdrNoThumbnail = 0;
        public const int Cdr1KMonoThumbnail = 1;
        public const int Cdr5KColorThumbnail = 2;
        public const int Cdr10KColorThumbnail = 3;

        // ── cdrFileVersion ──────────────────────────────────────────────────────────────
        public const int CdrCurrentVersion = 0;

        // ── cdrFillType (Phase 7) ───────────────────────────────────────────────────────
        public const int CdrNoFill = 0;
        public const int CdrUniformFill = 1;
        public const int CdrFountainFill = 2;
        public const int CdrPostscriptFill = 3;
        public const int CdrTextureFill = 8;
        public const int CdrPatternFill = 9;
        public const int CdrHatchFill = 10;

        // ── cdrColorType (Phase 7) ──────────────────────────────────────────────────────
        public const int CdrColorPantone = 1;
        public const int CdrColorCmyk = 2;
        public const int CdrColorRgb = 5;
        public const int CdrColorGray = 9;
        public const int CdrColorLab = 12;
        public const int CdrColorRegistration = 20;
        public const int CdrColorSpot = 25;
        public const int CdrColorMixed = 99;

        // ── cdrTextPropertySet (Phase 7) ────────────────────────────────────────────────
        public const int CdrTextPropertyAll = -1;
        public const int CdrTextPropertyFill = 1;
        public const int CdrTextPropertyOutline = 2;
        public const int CdrTextPropertyFont = 4;
        public const int CdrTextPropertySize = 8;
        public const int CdrTextPropertyStyle = 16;

        // ── cdrEffectType (Phase 4 — fluidity) ──────────────────────────────────────────
        public const int CdrBlend = 0;
        public const int CdrExtrude = 1;
        public const int CdrEnvelope = 2;
        public const int CdrTextOnPath = 3;
        public const int CdrControlPath = 4;
        public const int CdrDropShadow = 5;
        public const int CdrContour = 6;
        public const int CdrDistortion = 7;
        public const int CdrPerspective = 8;
        public const int CdrLens = 9;
        public const int CdrCustomEffect = 10;
        public const int CdrInnerShadow = 11;
    }
}
